@extends('layouts.app')

@section('content')
    <div class="container">
       <div class="jumbotron">
           <h3 class="display-4 text-center">Privacy Policy</h3>
           <hr class="my-2">
           <p>
            At Caspad, we are committed to protecting your information and respecting your privacy. By using our services, you agree to this privacy policy. The terms “Caspad”, “we”, “our” or “us” refer to Caspad Ltd. This privacy policy however, does not apply to any co-branded pages of our partners, affiliates, service providers and sponsors.
            This privacy policy explains our uses and practices regarding your personal information, data that we collect and all electronic media files sent to our site. If you do not agree to this privacy policy, please do not use our services.
           </p>

           <h3 class="display-5">Information Collection, Use and Sharing</h3>
           <hr class="my-2">
           <p>
            Caspad Ltd. is the sole owner of the information collected on this site. When you request information or content from Caspad and supply information or content that personally identifies you or allows us to contact you, you agree to share that information with Caspad, its agents, representatives, and affiliates. We only have access to information that you voluntarily give us via our online portal, marketing site, or related tools. You can log into your account, view any files and edit your personal information at any time. The account belongs to you and you have the right to review and change your personal information (contact information, name and password) at any time.
            To order transcription services, you must provide contact information (including but not limited to: name, phone number and email address) and financial information (including but not limited to: credit card number and PayPal information). We also collect feedback information you send us about your experience with the service. This information is used to process your transcription orders; deliver customer support; troubleshoot problems; resolve disputes; enforce our Terms of Service; analyze information to improve the Service; inform you about service updates, and promotional offers from us where you have not Opted out of receiving such information; verify your identity; provide additional features or services that we may develop.
            Electronic media files (audio recordings or video files) are used to effect transcription purposes only. Media files are used solely by the transcriptionists who transcribe the audio, and our quality control team and are deleted from our database after the completed transcript is delivered to the client. All transcriptionists are required to sign a Confidentiality Agreement. It is against our privacy policy to share clients’ media files with a third party.
            Some instances where we may disclose your information would be when we have to comply with a legal obligation (e.g. warrants, subpoenas and court orders); enforce our company policies; protect our or others rights, property and safety; protect against legal liability. Otherwise, financial information or personally identifiable information will not be provided to other parties for marketing, advertising or any other uses.
           </p>

           <h3 class="display-5">Cookies Privacy</h3>
           <hr class="my-2">
           <p>
            Cookies are small text files which are transferred from our websites, applications or services to your devices hard drive through your web browser (if you allow). Cookies enable a site or service provider systems to recognize your browser, capture and remember certain information. We use cookies to help us provide you with a personalized service, and to improve the user-experience on our websites, applications and services.
            Google Analytics uses cookies to help the website analyze how users use the websites, applications or services. The information generated by the cookie about your use of the websites, applications or services (including your IP address) will be transmitted to and stored by Google. Google will use this information for the purpose of evaluating your use of the websites, applications or services compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google’s behalf. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser or within the application, however please note that if you do this you may not be able to use the full functionality of this website. By using our websites, applications or services you consent to the processing of data about you by Google in the manner and for the purposes set out above.
            You may also configure your browser or our website, application or service to restrict cookies or block all cookies if you wish. However, if you disable cookies you may find this affects your ability to use certain parts of our website, applications or services. You can find more information about cookies and instructions on how to adjust your browser settings to accept, delete or reject cookies at the www.allaboutcookies.org.
            If you have any questions, requests regarding this privacy policy; or you feel we are not abiding by our privacy policy, contact us at info@caspad.com or via any other contact means provided on our website.
           </p>
       </div>

       <div class="jumbotron">
           <h1 class="display-5">Changes to Our Privacy Policy</h1>
           <hr class="my-2">
           <p>
            For any changes to our Privacy Policy, we will update the Policy modification date below. This Policy was last revised on 25th-April-2020.
           </p>
       </div>
    </div>
@endsection
